"""Add bestseller and new arrival to Product

Revision ID: 3a2e5acfab0a
Revises: 849ba2a4a81c
Create Date: 2025-05-28 19:12:17.627515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2e5acfab0a'
down_revision = '849ba2a4a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new_arrival', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_new_arrival')

    # ### end Alembic commands ###
