"""Add razorpay_order_id to Order model

Revision ID: 6191ec87a4eb
Revises: 3a2e5acfab0a
Create Date: 2025-06-03 10:55:50.635531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6191ec87a4eb'
down_revision = '3a2e5acfab0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_order_razorpay_order_id', ['razorpay_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('uq_order_razorpay_order_id', type_='unique')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
