"""Add is_bestseller and is_new to Product table

Revision ID: 849ba2a4a81c
Revises: aca118c27539
Create Date: 2025-05-28 18:58:49.477383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849ba2a4a81c'
down_revision = 'aca118c27539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_order_razorpay_order_id'), type_='unique')
        batch_op.drop_column('razorpay_order_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bestseller', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_new')
        batch_op.drop_column('is_bestseller')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_order_razorpay_order_id'), ['razorpay_order_id'])

    # ### end Alembic commands ###
