"""Add razorpay_order_id to Order model

Revision ID: aca118c27539
Revises: c165020d0f68
Create Date: 2025-05-27 22:33:40.388324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca118c27539'
down_revision = 'c165020d0f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['razorpay_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
